/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Forecast */
        post: operations["post_forecast_api_forecast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorResponseBody
         * @description The JSON body returned on any validation failure.
         */
        ErrorResponseBody: {
            /** Error */
            error: string;
        };
        /**
         * ForecastRequestBody
         * @description The JSON body `POST /api/forecast` accepts (contracts/forecast-api.md).
         */
        ForecastRequestBody: {
            /** History */
            history: number[];
            /** Period Days */
            period_days: number;
            /** Backlog Size */
            backlog_size?: number | null;
            /** Target Date */
            target_date?: string | null;
            /** Seed */
            seed?: number | null;
        };
        /**
         * ForecastResult
         * @description The outcome of a forecast request: outcomes at four confidence levels, plus basis.
         *
         *     `outcomes` always carries all four confidence levels — never a bare point
         *     estimate (Constitution Principle IV).
         */
        ForecastResult: {
            /** Outcomes */
            outcomes: {
                [key: string]: string | number;
            };
            /** Trials Run */
            trials_run: number;
            /** Periods Used */
            periods_used: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_forecast_api_forecast_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResult"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
