/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Forecast */
        post: operations["post_forecast_api_forecast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Forecast Csv
         * @description A CSV-dedicated endpoint (contracts/forecast-api.md), separate from
         *     `POST /api/forecast` - `multipart/form-data` so a real file upload needs
         *     no client-side text conversion (plan.md "Decisions confirmed" §1).
         */
        post: operations["post_forecast_csv_api_forecast_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_post_forecast_csv_api_forecast_csv_post */
        Body_post_forecast_csv_api_forecast_csv_post: {
            /** Period Days */
            period_days: number;
            /** Backlog Size */
            backlog_size?: number | null;
            /** Target Date */
            target_date?: string | null;
            /** Seed */
            seed?: number | null;
            /** Csv File */
            csv_file?: string | null;
            /** Csv Text */
            csv_text?: string | null;
        };
        /**
         * CycleTimeEntry
         * @description One resolved Jira issue's duration from its first in-progress transition to
         *     its resolution (spec 011 data-model.md). Exists only for issues with a known
         *     start - an issue that skipped "in progress" entirely is excluded upstream, not
         *     represented here with a missing or zero duration.
         */
        CycleTimeEntry: {
            /** Key */
            key: string;
            /**
             * Started At
             * Format: date
             */
            started_at: string;
            /**
             * Resolved At
             * Format: date
             */
            resolved_at: string;
        };
        /**
         * ErrorResponseBody
         * @description The JSON body returned on any validation failure.
         */
        ErrorResponseBody: {
            /** Error */
            error: string;
        };
        /**
         * FlowMetrics
         * @description Cycle-time, aging-WIP, and cumulative-flow views for one Jira request (spec
         *     011 data-model.md). A read-only, retrospective view - never consumed by
         *     `forecast_by_items`/`forecast_by_date` (Constitution Principle II).
         */
        FlowMetrics: {
            /** Cycle Time */
            cycle_time: components["schemas"]["CycleTimeEntry"][];
            /** Wip */
            wip: components["schemas"]["WipSnapshot"][];
            /** Flow State Counts */
            flow_state_counts: components["schemas"]["FlowStateCount"][];
            /** Excluded Count */
            excluded_count: number;
            /** Capped Count */
            capped_count: number;
        };
        /**
         * FlowStateCount
         * @description One day's count of tracked issues in each of the three flow bands (spec 011).
         */
        FlowStateCount: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Not Started */
            not_started: number;
            /** In Progress */
            in_progress: number;
            /** Done */
            done: number;
        };
        /**
         * ForecastRequestBody
         * @description The JSON body `POST /api/forecast` accepts (contracts/forecast-api.md).
         *
         *     `history` is optional - exactly one of it, or both `linear_api_key` and
         *     `linear_team_id`, is required (spec 006; enforced in `_compute_forecast`,
         *     matching the existing `backlog_size`/`target_date` "exactly one of"
         *     pattern rather than a separate pydantic validator).
         */
        ForecastRequestBody: {
            /** History */
            history?: number[] | null;
            /** Period Days */
            period_days: number;
            /** Backlog Size */
            backlog_size?: number | null;
            /** Target Date */
            target_date?: string | null;
            /** Seed */
            seed?: number | null;
            /** Linear Api Key */
            linear_api_key?: string | null;
            /** Linear Team Id */
            linear_team_id?: string | null;
            /** Linear Periods */
            linear_periods?: number | null;
            /** Jira Site */
            jira_site?: string | null;
            /** Jira Email */
            jira_email?: string | null;
            /** Jira Api Token */
            jira_api_token?: string | null;
            /** Jira Project Key */
            jira_project_key?: string | null;
            /** Jira Periods */
            jira_periods?: number | null;
        };
        /**
         * ForecastResponseBody
         * @description `ForecastResult`'s fields plus the actual per-period history used -
         *     whether typed in manually or fetched from Linear - so presentation
         *     layers (the web UI's charts, spec 005) can draw the burn-up/run charts
         *     without already knowing the counts client-side. Linear mode never gives
         *     the frontend the raw counts the way manual paste does (spec 006), so
         *     they're echoed back here instead. No change to `ForecastResult` itself
         *     (Constitution Principle II) - this is a web-layer-only addition.
         *
         *     `done_statuses` names the Jira statuses the history was built from (spec 010,
         *     clarification Q3); it is empty for every other source. `flow_metrics` (spec 011)
         *     is populated for Jira-sourced requests only; `None` for every other source.
         */
        ForecastResponseBody: {
            /** Outcomes */
            outcomes: {
                [key: string]: string | number;
            };
            /** Trials Run */
            trials_run: number;
            /** Periods Used */
            periods_used: number;
            /**
             * Reference Date
             * Format: date
             */
            reference_date: string;
            /** Distribution */
            distribution: components["schemas"]["OutcomeBucket"][];
            /** Projection */
            projection: components["schemas"]["ProjectionPoint"][];
            precision_warning?: components["schemas"]["PrecisionWarning"] | null;
            /** History */
            history: number[];
            /**
             * Done Statuses
             * @default []
             */
            done_statuses: string[];
            flow_metrics?: components["schemas"]["FlowMetrics"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OutcomeBucket
         * @description One bar of the outcome distribution (spec 005 data-model.md).
         */
        OutcomeBucket: {
            /** Lower */
            lower: string | number;
            /** Upper */
            upper: string | number;
            /** Trials */
            trials: number;
        };
        /**
         * PrecisionWarning
         * @description Advisory flag: a forecast's outcome spread is too wide to plan against.
         *
         *     Present only when the computed spread-to-center ratio exceeds the
         *     confirmed threshold (research.md §1/§2) - never a hard gate, always
         *     additive to the forecast it accompanies (Constitution Principle IV).
         */
        PrecisionWarning: {
            /** Message */
            message: string;
        };
        /**
         * ProjectionPoint
         * @description One future period of the burn-up fan (spec 005 data-model.md).
         */
        ProjectionPoint: {
            /** Period */
            period: number;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Cumulative */
            cumulative: {
                [key: string]: number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WipSnapshot
         * @description One currently-in-progress Jira issue's age as of today (spec 011).
         */
        WipSnapshot: {
            /** Key */
            key: string;
            /**
             * Started At
             * Format: date
             */
            started_at: string;
            /** Age Days */
            age_days: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_forecast_api_forecast_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponseBody"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_forecast_csv_api_forecast_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_forecast_csv_api_forecast_csv_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponseBody"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
