/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Forecast */
        post: operations["post_forecast_api_forecast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ErrorResponseBody
         * @description The JSON body returned on any validation failure.
         */
        ErrorResponseBody: {
            /** Error */
            error: string;
        };
        /**
         * ForecastRequestBody
         * @description The JSON body `POST /api/forecast` accepts (contracts/forecast-api.md).
         *
         *     `history` is optional - exactly one of it, or both `linear_api_key` and
         *     `linear_team_id`, is required (spec 006; enforced in `_compute_forecast`,
         *     matching the existing `backlog_size`/`target_date` "exactly one of"
         *     pattern rather than a separate pydantic validator).
         */
        ForecastRequestBody: {
            /** History */
            history?: number[] | null;
            /** Period Days */
            period_days: number;
            /** Backlog Size */
            backlog_size?: number | null;
            /** Target Date */
            target_date?: string | null;
            /** Seed */
            seed?: number | null;
            /** Linear Api Key */
            linear_api_key?: string | null;
            /** Linear Team Id */
            linear_team_id?: string | null;
            /** Linear Periods */
            linear_periods?: number | null;
        };
        /**
         * ForecastResponseBody
         * @description `ForecastResult`'s fields plus the actual per-period history used -
         *     whether typed in manually or fetched from Linear - so presentation
         *     layers (the web UI's charts, spec 005) can draw the burn-up/run charts
         *     without already knowing the counts client-side. Linear mode never gives
         *     the frontend the raw counts the way manual paste does (spec 006), so
         *     they're echoed back here instead. No change to `ForecastResult` itself
         *     (Constitution Principle II) - this is a web-layer-only addition.
         */
        ForecastResponseBody: {
            /** Outcomes */
            outcomes: {
                [key: string]: string | number;
            };
            /** Trials Run */
            trials_run: number;
            /** Periods Used */
            periods_used: number;
            /**
             * Reference Date
             * Format: date
             */
            reference_date: string;
            /** Distribution */
            distribution: components["schemas"]["OutcomeBucket"][];
            /** Projection */
            projection: components["schemas"]["ProjectionPoint"][];
            /** History */
            history: number[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OutcomeBucket
         * @description One bar of the outcome distribution (spec 005 data-model.md).
         */
        OutcomeBucket: {
            /** Lower */
            lower: string | number;
            /** Upper */
            upper: string | number;
            /** Trials */
            trials: number;
        };
        /**
         * ProjectionPoint
         * @description One future period of the burn-up fan (spec 005 data-model.md).
         */
        ProjectionPoint: {
            /** Period */
            period: number;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Cumulative */
            cumulative: {
                [key: string]: number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_forecast_api_forecast_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastRequestBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponseBody"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
